### ISSUE TITLE
a7105 and drv8231 avaibility/replacement

### ISSUE THREAD

**Issue by gsazi** [MarkR42/malenki-nano#11] opened 2023-11-22 10:40 UTC
Im trying to build some of those tiny wonders (malenki-hv), but those chips are not avaiable on JLCPCB for example, is there any other componnent that could replace them?

**Comment by MarkR42** [comment] 2023-11-22 11:50
You will need to get the assembly company to buy the components, or consign them to them. This is possible and others have done it.

Buying genuine Amiccom A7105 chips may be difficult unless you're prepared to buy a whole reel.  On the other hand, if you're prepared to gamble on used / counterfeit parts, there are suppliers.

I've been working with the other makers of the Malenki-Nano to consign parts to manufacturers as needed from an original reel of A7105.

The TI driver chips can probably be bought from catalogue suppliers and consigned, or your manufacturer may be able to purchase them in a cut tape themselves. We've had less issue with these.

**Comment by MarkR42** [comment] 2023-11-22 11:51
Obviously it's open source and you're welcome to modify the design to use different components. However, replacing the radio chip isn't trivial.

**Comment by MarkR42** [comment] 2023-11-22 11:52
I hope this helps, I'm closing this issue as it really isn't my problem.

**Comment by MarkR42** [comment] 2023-11-22 11:53
Closing as not a bug.

**Closed** 2023-11-22 11:53 UTC
